### ISSUE TITLE
Icons on the schedule

### ISSUE THREAD

**Issue by FatBoyXPC** [cubing/ccm#184]
Putting the event icons on the schedule has been discussed a bit. I went ahead and started playing with this (just the markup for now). 

https://imgur.com/fgEWpGa is how it looks on a half hour duration. I'm not sure I like that for larger cubes. Just to put that in perspective: https://imgur.com/FZc4jQm.

For good measure, here is an hour duration: https://imgur.com/M6MdERk.

I'm not entirely convinced that it the icon looks good. Yes, I can make the font smaller, but 777 is hard enough to see as it is.

Thoughts?

**Comment by jfly** [comment]
I like it! Competitions generally won't be running 30 minutes of 777, so I don't think we really need to worry about this use case =)

**Comment by FatBoyXPC** [comment]
What about for a final round of say 8 competitors?

**Comment by jfly** [comment]
Yeah, tough call. I am a big believer in not letting the perfect get in the way of the good, and this seems like an improvement on what we have right now, so I'd vote for https://imgur.com/FZc4jQm over what we have now.

**Comment by larspetrus** [comment]
This is assuming the problem here is that it's not easy to see at a glance when all the 4x4x4 rounds are. If people want icons for other reasons, this may not apply.

The icons don't really "pop" for me. They're not much easier to spot that the text.

I think doing something with color would be the best for that. So 4x4x4 could always be green, for example. You can have the icons in certain colors, the background, the frame, etc. Many things to try out.

Other ideas:
- When hovering over one 5x5x5 round, it and its siblings should light up.
- Final rounds could have a special look
- Rounds I'm qualified for should have a special look, as should one I'm excluded from.
