### ISSUE TITLE
SolveTimes should have an timestamp field

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#194]
Knowing when a solve was done may be useless, but seems like too cool of information to just throw away.

@patriciali, FYI

**Comment by patriciali** [comment]
Why can't the server fill in the timestamp from when the request was sent
to upload the time?

**Comment by FatBoyXPC** [comment]
@patriciali Good point, and that's definitely the better way to set the timestamp.

**Comment by pochmann** [comment]
What if you lose connection to the server? And to me it just makes more sense to timestamp at the source.

**Comment by FatBoyXPC** [comment]
Well, the main issue here is, if it loses connection to the server, then you won't be able to judge anybody else until you get that connection back. I suppose that could be fixed by downloading all the data to Wingman, but I assumed that every time we entered a participant ID that it would hit the database.

I'm just personally a fan of setting stuff on the server as it forces data integrity that way.

**Comment by pochmann** [comment]
The solve timestamp is very closely tied to the solve result. I think it should be recorded right where the solve happened. If data integrity is lost at all, then I'd say it's if you record solve result and solve timestamp at *separate* places.

**Comment by FatBoyXPC** [comment]
> If data integrity is lost at all, then I'd say it's if you record solve result and solve timestamp at separate place

I disagree. We can't force the client to have the proper time set, or the time zone, etc. We have 0 control over the client, but the server will enforce the same 'rules' across all incoming data. If we are going to send times from the client to the server, then we should also send the "current" time to make sure that none of the time settings are screwed up.

Alternatively, we could not place a lot of concern on something like this as it's not important data, so we can just handle it however is easiest (I would assume at the database).

**Comment by pochmann** [comment]
Also, as far as I understand, Wingman will be connected to the stackmat, right? Will it (try to) transmit the result to the server immediately, and in case of penalties, submit the changed result in a second transmission? Or will it wait for an OK by the judge and competitor before it sends the result to the server? If it does the latter, then several seconds might be wrongly added to the solve timestamp. Even more in case of disputes.

**Comment by FatBoyXPC** [comment]
To my knowledge it will wait until the solve is complete to send one complete set of data to the server. And honestly - I don't think that time delay matters, as a solve is not complete until it is recorded by the judge on a scorecard.

**Comment by pochmann** [comment]
The solve is complete when the solve is complete. Not when the result is recorded.

**Comment by FatBoyXPC** [comment]
We don't need to be muddying up this thread with debating when a solve is complete. Thank you for your opinions.

**Comment by pochmann** [comment]
Well I think in a thread about recording something, it does make sense to talk about what that something is.

Besides disputes I just remembered that celebrations can also create big delays. It can take quite a while until someone is done jumping around and getting hugged by everyone until they sign the scoresheet.

**Comment by FatBoyXPC** [comment]
The entire solve includes penalties. Clearly it cannot be finished until penalties are determined and appropriately recorded.

Anyways, it's senseless to argue it, since it is defined in the regulations. You are usually the first one to bring up the regulations, I'm surprised you didn't in this case.

**Comment by patriciali** [comment]
I originally brought up the question because it's not clear to me how this information will ever be useful, other than "just for fun", and while I realize taking the timestamp of the time the request to the server isn't totally accurate, it's accurate enough for "just for fun". We could very well do it client-side, but as @FatBoyXPC brought up then we'd either have to worry about timezones, or get the time from a server (CCM or some other place), which would involve more complications, which I'm always hesitant to do unless it is necessary, which in this case I don't think it is.

**Comment by pochmann** [comment]
James: With phrases like "penalties during/after the solve" the regulations actually make it quite clear that such penalties are, well, *after* the solve.

Patricia: Jeremy and I talked last night about determining records more fine-grained than the current "end of the day" rule and we went all the way down to involving individual solve timestamps. That's one reason I care about accuracy.

**Comment by FatBoyXPC** [comment]
I think you missed the "This finishes the attempt" part of that regulation.

**Comment by pochmann** [comment]
That says attempt, not solve.

**Comment by patriciali** [comment]
> Jeremy and I talked last night about determining records more fine-grained than the current "end of the day" rule and we went all the way down to involving individual solve timestamps. That's one reason I care about accuracy.

Ah, ok, I see. What do the regs say?

**Comment by FatBoyXPC** [comment]
Quit being pedantic, you know they're synonymous here.

**Comment by pochmann** [comment]
I don't think so. And not just because I'd be wondering why the regulations would unnecessarily be using two different words. But thank you for your opinion.

Patricia: The current regs are "end of the day". But I'd like to change that. I don't see any good reason why for example a WR in the first round should be nullified by a better result in the second round hours later.

**Comment by jbcm627** [comment]
>The current regs are "end of the day". But I'd like to change that. I don't see any good reason why for example a WR in the first round should be nullified by a better result in the second round hours later.

This would be neat, but I'm not sure it would be practical.  I'm not sure we should require all competitions to purchase hardware necessary for this.  I think it may be realistic to require a competition to record a timestamp when the data is entered at least, but I'm not sure we should ever require something like wingman.

**Comment by pochmann** [comment]
I think eventually the vast majority will use Wingman or something equivalent, and it might not take that long. I assume it's cheaper than the speedstacks displays, and those are ubiquitous. Also, it doesn't need to be ubiquitous to be useful. It's just that if we do use solve timestamps for this, I'd like them to be accurate and not throw accuracy away unnecessarily.

All that said, this would require a regulations change, which I doubt would happen anytime soon if at all. So I guess at least for now it doesn't really matter that much. It just irks me to lose information (and in case anyone wonders, yes, I also dislike that we currently lose penalties information and for example "2/5" multiblind information and I'm undecided about the millisecond information).

**Comment by jfly** [comment]
It sounds like there are a lot of potential issues with asking Wingman to timestamp (timezones/incorrect clocks). The most compelling reason I heard for pushing the timestamping over to wingman is to handle the case where wingman is offline. However, there are no plans for wingman to work offline. If we do want wingman to work offline, adding timestamping to wingman will be the *least* of our concerns if we do go down that path.

Please see https://github.com/cubing/ccm/pull/196.

**Comment by jfly** [comment]
@pochmann , I agree about not throwing information away. That's why CCM already does store times in the granularity given to it by the client (wingman will support both gen2 and gen3 timers), and stores the penalties and solved/attempted for mbld.

**Comment by FatBoyXPC** [comment]
@pochmann I somewhat disagree about the use of Wingman/equivalents. First, to my knowledge, Wingman will not be replacing displays, but rather be used in conjunction with them. Second, while Cubecomps is quite popular, there are still people that use the workbook. While I'd love for all of cubing to adopt the new idea immediately, I'm of the opinion that adoption will be somewhat slow. I do, however, feel that CCM/Wingman at US Nats would speed that adoption up, at least in the US.

**Comment by pochmann** [comment]
Sorry I wasn't clear, I didn't think Wingman would replace displays, I just meant that we can afford the displays so we can probably also afford Wingman (additionally). I don't know why people still use the workbook, do you? Is it because it can be used offline or because they're used to it? CCM should solve the offline issue and if we "encourage" people to use it, I think they will.

**Comment by FatBoyXPC** [comment]
I don't know why, no. I think most of it is because they are used to it. There have been arguments made for offline use, but yes, CCM will take care of that :)
