### ISSUE TITLE
Consider tracking workflows

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#57]
It may be beneficial to track what features are used, and how - basically monitoring traffic or workflow.  This information can be useful for improving usability - identifying ways to streamline or automate common tasks.

**Comment by jfly** [comment]
I'm adding this to Phase 1. We really out to figure this stuff out before we release, otherwise we'll have no idea how we're doing. With https://github.com/cubing/ccm/commit/b96dc066c8bdfdf80f7eed1f568c97717a33a984, I added google analytics to live.cubing.net, but I would really like to track api calls as well.

**Comment by jfly** [comment]
We'll add this stuff as we see fit.
