### ISSUE TITLE
Determining competition/person locations.

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#96]
gjcomps may need to be aware of continents and countries for things like #22, #24; and also #20 for marking potential new records in live results.

Things to do: 
  - [x] Make code reactive; the map location doesn't change when another user saves
  - [ ] Attempt to use 2sphere? http://docs.mongodb.org/manual/tutorial/build-a-2dsphere-index/
  - [ ] We may want to allow competitions to specify custom address / text information about a competition's location
  - [ ] Fullscreen button (so people can use their scrollwheel =))
  - [ ] Get city/state/country, using the google maps [geocoder service](https://developers.google.com/maps/documentation/javascript/reference#Geocoder) to extract country, "administrativeArea", and "locality" ("sublocality"?) types.
  - [ ] At some point it may be neat to implement more granular unofficial records, like CubingUSA does with states.

**Comment by jbcm627** [comment]
Some of this is done for competitions in 63e7b6a.  We can get city / state / country by reverse geocoding.

**Comment by jbcm627** [comment]
One issue that just came up for the WCA website: competitions with multiple locations?  Eg:
https://www.worldcubeassociation.org/results/c.php?i=FMCUSA2014
https://www.worldcubeassociation.org/results/c.php?i=CrossstraitFMC2014
https://www.worldcubeassociation.org/results/c.php?i=FMCEurope2015

**Comment by jfly** [comment]
This sounds good to me. We should make it clear on the schedule page which time zone everything is in, and make it easy to see the schedule in the time zone of a particular venue. http://fmce.cubecomps.com/2015 does a good job of this.

**Comment by jfly** [comment]
@jbcm627 and I just tossed around the idea of combining multiple venues and #28 (multiple rooms).

There's some trickiness to this:

- Venues normally have identical schedules, whereas rooms will normally never run the same round. James and I agree that if someone wants to run a round in multiple rooms, they'll have to create new "rounds" by hand.
- Timezones. It's easiest for me to think about things if each venue just defines a new timezone, rather than a new schedule. At the same time, I don't know if we want to require that all venues have the exact same schedule...

For now, we're going to focus on #28 (which is also not a priority for Phase 1). I'm going to leave this issue blocking Phase 1 because it has some features that do need to be fixed for Phase 1.
